# Generated by Django 2.2.2 on 2019-09-03 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190903_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=255, null=True)),
                ('div', models.CharField(max_length=255, null=True)),
                ('rollno', models.IntegerField(default=0)),
                ('ParentileContact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('bloodgroup', models.CharField(max_length=255, null=True)),
                ('familyIncome', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Studentprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
